spring:
  application:
    name: greenwich_fitness_api
  datasource:
    url: jdbc:mysql://localhost:3306/greenwich_fitness
    username: root
    password: 12345
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieplt.developer@gmail.com
    password: Greenwich31121995
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /greenwich-fitness/api/v1